name: Deploy to Azure App Service

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: testreactappserv
          slot-name: <optional-slot-name> # If deploying to a slot
          publish-profile: {
                            "clientId": "d5c25802-78e9-4eaa-873e-c7a9cd2d0a84",
                            "clientSecret": "s848Q~JiUkaImN4fCHZGpSba4X0GSkjoFJz~zbej",
                            "subscriptionId": "61fc7a8e-363a-4dce-849e-5b13de154857",
                            "tenantId": "fc190238-d438-4d14-81a5-62d574913928",
                            (...)
                           }
          package: .
